name: build-linux-images

on:
  push:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: docker login -u=${{ secrets.DOCKERHUB_USERNAME }} -p="${{ secrets.DOCKERHUB_PASSWORD }}"
      - name: Build the tagged Docker image
        run: docker build . -t romainbsl/kmp-native:linux-1.3.71 -f linux/kmp-native
      - name: Push the tagged Docker image
        run: docker push romainbsl/kmp-native:linux-1.3.71
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: docker login -u=${{ secrets.DOCKERHUB_USERNAME }} -p="${{ secrets.DOCKERHUB_PASSWORD }}"
      - name: Build the tagged Docker image
        run: docker build . -t romainbsl/kmp-native:windows-1.3.71 -f windows/kmp-native
      - name: Push the tagged Docker image
        run: docker push romainbsl/kmp-native:windows-1.3.71