name: TEST GA

on:
  push:
    branches: [ test ]

jobs:
    linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: echo env
              run: echo ${{ github.run_id }} + ${{ github.run_number }}